version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: notification_service_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL : jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME : notification_service_user
        SPRING_DATASOURCE_PASSWORD : mypassword
    ports:
      - "8080:8080"

  contact-service:
    build:
      context: ./contact-service
      dockerfile: Dockerfile
    container_name: contact-service
    restart: always
    depends_on:
      - postgres
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: notification_service_user
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8081:8080"

volumes:
  postgres_data:
    driver: local