version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: notification_service_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    environment:
        SPRING_DATASOURCE_URL : jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME : notification_service_user
        SPRING_DATASOURCE_PASSWORD : mypassword
    ports:
      - "8080:8080"

  contact-service:
    build:
      context: ./contact-service
      dockerfile: Dockerfile
    container_name: contact-service
    restart: always
    depends_on:
      - postgres
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: notification_service_user
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8081:8080"

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  kafka-config-service:
    build:
      context: ./kafka-config-service
      dockerfile: Dockerfile
    container_name: kafka-config-service
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8080"


  notification-handler:
    build:
      context: ./notification-handler
      dockerfile: Dockerfile
    container_name: notification-handler
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8085:8080"

  notification-scheduler:
    build:
      context: ./notification-scheduler
      dockerfile: Dockerfile
    container_name: notification-scheduler
    restart: always
    depends_on:
      - contact-service
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CONTACT_GRPC_SERVER: contact-service:50051
    ports:
      - "8086:8080"

volumes:
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local